### ISSUE TITLE
7.5m parts miscategorized as 10m

### ISSUE THREAD

**Issue by tagehring** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#146]
I can find the E-series tanks and other parts within each category under Filter By Function, but when I try the Size 5 category via Filter By Cross-Section Profile or the 7.5m filter using Moar Filter Extension Configs, they don't seem to be there. I do see them under the Size 6 and 10m categories.

Here is the part info for one of the tanks:

```
Mod: NearFutureLaunchVehicles
Name: nflv-fueltank-75-2
Path: NearFutureLaunchVehicles/Parts/FuelTank/nflv-fueltank-75-2/nflv-fueltank-75-2
Size: 13.18
Bulkhead Profiles: size6, srf
-----------------------------------------------
Mass: 36.000 t
Resources:
    LiquidFuel: 25920.0/25920.0, mass: 129.600 t
    Oxidizer: 31680.0/31680.0, mass: 158.400 t
-----------------------------------------------
```

Game version is 1.12.5; I have Filter Extensions - Plugin, Filter Extensions - Default Configuration, Filter Extensions - Stock Rework, and Moar Filter Extension Configs all installed at their latest versions via CKAN. I tried to attach ksp.log, but it's 56 MB.

The 5m N-series tanks and other parts appear within the correct size categories.
